# -*- coding: utf-8 -*-
"""Assignment2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tkRZsBjsdhAzWDyBMJp3x-fUvq-OMzhc

##Q1 What are the two values of the Boolean data type? How do you write them?

Answer --> True & False

## Q2 What are the three different types of Boolean operators?

AND, OR, NOT

##Q3 Make a list of each Boolean operator&#39;s truth tables (i.e. every possible combination of Boolean
values for the operator and what it evaluate ).

True and True is True.

True and False is False.

False and True is False.

False and False is False.

True or True is True.

True or False is True.

False or True is True.

False or False is False.

not True is False.

not False is True.

##Q4 What are the values of the following expressions?
i. (5 &gt; 4) and (3 == 5), 
ii. not (5 &gt; 4), 
iii. (5 &gt; 4) or (3 == 5), 
iv. not ((5 &gt; 4) or (3 == 5)), 
v. (True and True) and (True == False), 
vi. (not False) or (not True)

i)False
ii)False
iii)True
iv)False
v)False
vi)True

Q5 What are the six comparison operators?

Ans ==, !=, <, >, <=, and >=
"

##Q6 Q6. How do you tell the difference between the equal to and assignment operators?Describe a condition and when you would use one.
"""

"""
equal to is actually a comparision operator, represented by '==' & assignment is represented by '='
When we want assign value to a variable we'll use '='
When we want to compare two entities we'll use '=='
"""
#example of assignment operator
a = 3  
print(a)

#example of equal to OR comparision operator. 
for i in range(2):
  if i == 1:
    print(f"Check Complete 'i' == {i}")    
    break

"""##Q7 Identify the three blocks in this code"""

spam = 0
if spam == 10:
    print('eggs') #Block 1
if spam > 5:
    print('bacon') #Block 2
else:
    print('ham') #Block 3
    print('spam')
    print('spam')

"""##Q8. Write code that prints Hello if 1 is stored in spam, prints Howdy if 2 is stored in spam, and prints Greetings! if anything else is stored in spam."""

spam = int(input("Input a no."))
if spam == 1:
    print("Hello")
elif spam == 2:
    print("Howdy")
else:
    print("Greetings!")

"""##Q9.If your programme is stuck in an endless loop, what keys you’ll press?

Ans. If program is stuck in endless loop we will press ctrl+c.

##Q10 How can you tell the difference between break and continue?
"""

"""
break --> break key word breaks the current loop

continue --> continue keyword is usally use to not to take any action if certain criteria is satisfied.
"""

# use of break
for i in range(3):
    if(i==2):
        break
    print(i)
    
print('Breaked')
#use of  continue
for i in range(5):
    if(i==4):
        continue
    print(i)

"""##Q11. In a for loop, what is the difference between range(10), range(0, 10), and range(0, 10, 1)?"""

"""
All three of them wll give same output.
i. range(10) will start loop from 0 continue till 9
ii. range(0,10) will start loop from 0 continue till 9
iii. range(0,10,1) will start loop from 0 continue till 9 & stepsize will be 1. 

Default stepsize is 1.

"""
for i in range(10):
    print(i)
print("--------------------------") 
for i in range(0,10):
    print(i)
print("-------------------------")
for i in range(0,10,1):
    print(i)

"""##Q12. Write a short program that prints the numbers 1 to 10 using a for loop. Then write an equivalent program that prints the numbers 1 to 10 using a while loop."""

#For Loop
print("For Loop")
for i in range(1,11):
    print(i)

#While Loop
print("While Loop")
a =1
while a <= 10:
    print(a)
    a+=1

"""##Q13. If you had a function named bacon() inside a module named spam, how would you call it after importing spam?

"""

"""
spam.bacon()

where, 
spam is module name
bacon is function name
""

